# Generated by Django 2.2.7 on 2019-11-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonfile', models.FileField(blank=True, default='', null=True, upload_to='App/json/')),
                ('docxfile', models.FileField(blank=True, default='', null=True, upload_to='App/docx/')),
                ('pdfFile', models.FileField(blank=True, default='', null=True, upload_to='App/pdf/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
        ),
    ]
